### ISSUE TITLE
Integrations Settings Page

### ISSUE THREAD

**Issue by bryceadams** [mikejolley/WP-Job-Manager#353]
Just thinking it may be good to have an Integrations Settings API like you did with WC. When a user has a lot of extensions activated, all creating their own settings page, it gets pretty crowded and 'in your face'.

One issue is that some users may struggle to figure out they need to go to **Settings > Integration > [Integration Name]**, but having a link from the Plugins page and clear docs will help this.

**Comment by mikejolley** [comment]
Possibly a future item - for now there are not enough addons to justify this IMO.

**Comment by bryceadams** [comment]
Taking the easy way out


Best,Bryce
