### ISSUE TITLE
Display Particular Category in Page

### ISSUE THREAD

**Issue by ngsoftech** [mikejolley/WP-Job-Manager#354]
Hello,
          This is my site "http://tazajobs.com/" I want to display Particular Category in pages for eg.
"http://www.tazajobs.com/job-category/bank-jobs/"  this is my "Bank Jobs " Category I want to display this Category job in my "bank-jobs" Page Please suggest me.

**Comment by bryceadams** [comment]
Please direct support requests here - https://wordpress.org/support/plugin/wp-job-manager
