### ISSUE TITLE
Adding map pin location to job submission form

### ISSUE THREAD

**Issue by studioleland** [mikejolley/WP-Job-Manager#357]
Using listify for a project that requires the listing of local parks on the map.  It would be very helpful to allow visitor to pinpoint the location on the actual map by dragging the map pin to the specific spot after entering via address or location text input.  Is this on the radar or is there a reason this wouldn't be possible?  Feedback on this feature expansion helpful.  Thanks guys.

**Comment by mikejolley** [comment]
This would require a few additions;

1. You'd need to add a google map widget to your job submission form (template override)

2. You'd probably want to disable built in geolocation via the job_manager_geolocation_enabled filter

3. You'd want your map widget to populate some hidden fields (location string, lat/long)

4. You'd save this data to the job listing once the form is posted.

This would give you full control over geolocation.

**Comment by bilgot** [comment]
Solution is here: http://listify.astoundify.com/article/817-why-is-there-no-map-on-my-submit-listing-form

**Comment by bilgot** [comment]
http://listify.astoundify.com/article/817-why-is-there-no-map-on-my-submit-listing-form
