### ISSUE TITLE
Add the ability to remove the 'change' binding on inputs

### ISSUE THREAD

**Issue by spencerfinnell** [mikejolley/WP-Job-Manager#363]
Having the fields auto update on change causes issues for certain things we try to do with maps. Specifically (but not limited to) the AutoComplete API from Google. If you start typing and tab down to a result you're changing the input so it'll start searching for the first part of the string instead of the selected item.

**Comment by mikejolley** [comment]
This can already be done - unbind the change events and add your own replacements. Just ensure you trigger the update event with your new code:

`
var target = $( this ).closest( 'div.job_listings' );
target.triggerHandler( 'update_results', [ 1, false ] );
`
