### ISSUE TITLE
 BUG - Issue with integration with Listify theme

### ISSUE THREAD

**Issue by galapriti** [mikejolley/WP-Job-Manager#365]
Hey, i am using this plugin with listify theme. the problem here is,, 
In the option listing Categories, it shows no of entries in it correctly, but whn opened shows only listings selected in parent category, if any child category is selected , it does not appear there. 
kutchi.biz.
Please help i am stuck with this project here. 

![kutch1](https://cloud.githubusercontent.com/assets/10562777/5778069/77d3023e-9dbe-11e4-983b-84e7c8e0a089.png)

![kutch2](https://cloud.githubusercontent.com/assets/10562777/5778068/77c67320-9dbe-11e4-993d-2f02e0c2a758.png)

**Comment by adampickering** [comment]
Please contact support if you have support questions (if you haven’t already). Posting this issue on WP Job Manager's github is the incorrect place to get help with the Listify theme, you are also using a very old out of date version of the theme which would be causing these issues.

If you are looking for theme support, please <a href="https://support.astoundify.com/register/">REGISTER</a> at our help desk or browse our <a href="http://docs.astoundify.com/">theme resources centre</a> which contains many detailed video tutorials and theme documentation. Once logged in, feel free to create a new support ticket <a href="https://support.astoundify.com">HERE</a>.

Already registered? You can <a href="https://support.astoundify.com/wp-login.php">LOGIN HERE</a>. We appreciate your business and look forward to serving you.
