### ISSUE TITLE
Application Deadline automatic expiration not working

### ISSUE THREAD

**Issue by satshost** [mikejolley/WP-Job-Manager#368]
Hi,

I cannot seem to get the automatic expiration in the Application Deadline to work. I have tried to disable/enable and delete/reinstall the add-on. And have posted several jobs these last days to test. Any suggestions to what I can try to do next?

**Comment by mikejolley** [comment]
Install DEBUG BAR and DEBUG BAR CRON and see if the cron jobs are running.

**Comment by satshost** [comment]
thx! seemes to be something wrong with many cron jobs in this installation.
