### ISSUE TITLE
Template filter does not filter all template files!

### ISSUE THREAD

**Issue by jannnik** [mikejolley/WP-Job-Manager#369]
It seems like the template path filter only filters the "job-filters"-templates, but not the "content"-templates. Please add support to filter all templates! :-)

**Comment by tripflex** [comment]
You can filter all of the templates, you are probably just not doing it correctly.  Please describe more in details what you are trying to do so we can point you in the right direction.

https://github.com/mikejolley/WP-Job-Manager/blob/master/wp-job-manager-template.php#L62

**Comment by jannnik** [comment]
If you need more info, look at this thread: 
https://wordpress.org/support/topic/plugin-template-path?replies=7#post-6463440

**Comment by jannnik** [comment]
does this mean that I have to filter ´locate_job_manager_template()´ instead of ´job_manager_locate_template()´?

**Comment by mikejolley** [comment]
No - use the same filter (job_manager_locate_template)
