### ISSUE TITLE
Can I avoid lazy loading by configuration?

### ISSUE THREAD

**Issue by iwxfer** [mikejolley/WP-Job-Manager#371]
I don't want lazy load for Job Listing, I would like to have different URLs for every search. Is it configurable? or any idea to develop?

**Comment by batsteek** [comment]
https://wpjobmanager.com/document/shortcode-reference/ is maybe what you are looking for ?

**Comment by fourleafed** [comment]
I think you are referring to AJAX that loads the jobs when using the [jobs] shortcode. You could create one or several page templates with WP_Query to match you preferences. Keep in mind that will have to add the search form manually! I use the following to get the jobs:

    $args = array (
        'post_type'        => 'job_listing',
        'post_status'     => 'publish',
    );

    // The Query
    $query = new WP_Query( $args );
    // The Loop
    ...
    wp_reset_postdata();

If you only want to display featured jobs you can use meta_query like so:

    $args = array (
        'post_type' => 'job_listing',
        'post_status' => 'publish',
        'meta_query' => array(
            array(
                // only show jobs when custom meta '_featured' = 1
                'key' => '_featured',
                'value' => '1',
                'compare' => '=',
            ),
        ),
    );

    // The Query
    $query = new WP_Query( $args );
    // The Loop
    ...
    wp_reset_postdata();

**Comment by mikejolley** [comment]
Yup, or you can enable full template support (so that the post archives are enabled) and then you don't need shortcodes to list jobs at all. https://github.com/mikejolley/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L65

Good luck
