### ISSUE TITLE
Please create FILLED jobs shortcode

### ISSUE THREAD

**Issue by cmeurer** [mikejolley/WP-Job-Manager#374]
I would like to show a table of all closed/filled positions so that my clients can see the types of jobs I typically have (even if not available at the moment), as well as for SEO/keyword purposes. Thank you!

**Comment by cmeurer** [comment]
Can you clarify what exact code I should use for this? THANK YOU for doing this, and so quickly too!!

**Comment by mikejolley** [comment]
[jobs filled="true"]

**Comment by cmeurer** [comment]
THANKS!

**Comment by cmeurer** [comment]
Hi! I emailed you but then realized this is probably a better way to communicate. 
You helped me out a while ago by creating the option to have a page show the FILLED jobs. You told me to use [jobs filled="true"]. I tried but it isn’t working. Do I need to update my plugin perhaps? Here is the page that SHOULD be showing just filled jobs, but instead is showing all the open ones:  http://advocatestaffing.com/dev/filled-jobs/
 
Also, is there a way to clone a job listing so I don’t have to cut/paste to another listing if they are almost identical?

**Comment by mikejolley** [comment]
Its in the current version - don't recall which is was added to. 

https://wordpress.org/plugins/duplicate-post/

**Comment by cmeurer** [comment]
So do I just do an upgrade - none of my work will be lost, correct? Thanks!

**Comment by bryceadams** [comment]
Updates shouldn't result in anything lost but of course, keep a back up to be safe.

**Comment by cmeurer** [comment]
Thanks - I updated and now they appear but can they NOT be faded out? http://advocatestaffing.com/dev/filled-jobs/
Is that just a CSS change? I just want them to appear normally on a page, as it's good to show people what we've worked on in the past, and great for SEO with all the keywords in the content.

**Comment by mikejolley** [comment]
Yes you can add css to your theme to remove the opacity rule.

**Comment by cmeurer** [comment]
I put this in and it's still faded... help?
ul.job_listings li.job_listing.job_position_filled a,ul.job_listings li.no_job_listings_found.job_position_filled a{opacity:1}

**Comment by cmeurer** [comment]
Nevermind! I added the semicolon and !important and it's all good now. Thank you so much again. It's so nice that you added this for me :)
