### ISSUE TITLE
Option to suppress posting date in list view

### ISSUE THREAD

**Issue by elmktg** [mikejolley/WP-Job-Manager#376]
Could there be an option to not display the posting date (e.g. "1 month ago") in the list of jobs? The posting date on the detail page isn't so bad, but in an overview listing of jobs, the post-date is often undesirable.

**Comment by mikejolley** [comment]
I don't think an option is justified - you can remove it with simple CSS or customise the template file if you don't want it.

**Comment by elmktg** [comment]
OK, we got it done that way. I just thought it might be easy to make an option for the more technically-challenged, and/or in case that template file gets updated for other reasons.

**Comment by mikejolley** [comment]
Something to consider, but I'm wary of adding too many options.

**Comment by fourleafed** [comment]
This should be a theme setting, not a plugin setting. And since almost all themes offer a custom CSS section:

**Quickest fix**
```
.class-name-of-whatever-you-want-to-hide, #or-the-id-of-that-annoying-piece-of-HTML {
    display: none;
}
```
