### ISSUE TITLE
job_types are not reset by the "rest" option

### ISSUE THREAD

**Issue by kochhase** [mikejolley/WP-Job-Manager#377]
Hi Mike Jolley,
i think find a buy., I think it is a bit older, by testing the reset option for searching. the job_types are not resetted after you have used them. the same is when i using the addon Geo job manager for the seach options like radius or sorted by.
thank you for help

**Comment by mikejolley** [comment]
Just tested this and there is no bug in the latest release- ensure the other plugins/themes you have running are not affecting yours.

**Comment by kochhase** [comment]
are you shure that the addon Geo job manager latest (1.5.1) is working (reset) with WPJM?

**Comment by mikejolley** [comment]
I cannot tell you - I didn't write geo job manager.
