### ISSUE TITLE
Categories, Tags, and Filters for Resume Listing?

### ISSUE THREAD

**Issue by ifrankieg** [mikejolley/WP-Job-Manager#380]
Hi Mike Jolley,

Very nice work! It would be cool if categories, tags, and filters could be added to the resume list as well. There are lots of job training organizations out there who could provide potential recruiters more filtering control when vetting through possible candidates (e.g. filter by years of experience, education level, skills, etc). I've been searching for a plugin that can accommodate robust (yet clean and simple) listings for BOTH job openings AND resume listings for a non-profit job training client. Thoughts?

![cats-tags-filters-for-resumes](https://cloud.githubusercontent.com/assets/10767667/5971129/0ed1be7a-a80d-11e4-8f7c-dac55f3a2a36.jpg)

**Comment by fourleafed** [comment]
Hi @ifrankieg , nice suggestion, but the resume plugin is a premium plugin. Please contact Mike & Bryce via their website.

@mikejolley: how 'bout bbpress… ;-)

**Comment by mikejolley** [comment]
Resumes has categories too :)

I'll log skills in the correct repo. Thanks
