### ISSUE TITLE
Application post status error due to .mo translation

### ISSUE THREAD

**Issue by Mesetudes** [mikejolley/WP-Job-Manager#385]
When you translate APPLICATION Add-on, specificaly the status of an application the system put the translate application status in the database, and once saved the system do not recall the post beacause of the status. When I change back the post status in the DB, all is back to normal.
So you might change the code to send hardcode status in the DB, because even when I change the status to the original on the front end it still translated wich is great. So it seems only a minor bug.
Thanks

**Comment by mikejolley** [comment]
Found and patched applications last week thanks :)
