### ISSUE TITLE
Non-ajax search form

### ISSUE THREAD

**Issue by fourleafed** [mikejolley/WP-Job-Manager#387]
Make a non-ajax search form that can be used when using jobs page with custom WP_Query.

#suggestion/enhancement

**Comment by mikejolley** [comment]
Without theme support, JM needs to be self-contained within shortcodes. Thats why filters use ajax.

If you have a custom display, you can also make custom fields and pass the values to the get_job_listings function https://github.com/mikejolley/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L9

**Comment by fourleafed** [comment]
I'll look into those. I think a non-ajax shortcode can be better for SEO; see this cached frontpage of [a demo site](http://webcache.googleusercontent.com/search?q=cache:ahk1VUea_NEJ:ggz-vacatures.nl/+&cd=5&hl=nl&ct=clnk&gl=nl). No jobs…

**Comment by mikejolley** [comment]
@fourleafed Surely the main content for SEO are the single job listings? There is not really anything of value on the listing page. Use a sitemap plugin to ensure Google can find them :)
