### ISSUE TITLE
Double meta and company class elements in WP V 4.1

### ISSUE THREAD

**Issue by StobyWan** [mikejolley/WP-Job-Manager#388]
see example
http://www.laytoncenter.org/job/youth-specialist/

**Comment by bryceadams** [comment]
@StobyWan this doesn't look to be a bug. Best thing you can do is temporarily switch to the default Twenty Twelve theme and deactivate all other plugins and see if that fixes it. If not, open up a thread here - https://wordpress.org/support/plugin/wp-job-manager - and hopefully we can help.

**Comment by mikejolley** [comment]
I replied on your WordPress.org thread. Thanks.
