### ISSUE TITLE
Indeed Add-On: Default job type

### ISSUE THREAD

**Issue by mirandag55225** [mikejolley/WP-Job-Manager#389]
I have spoke with Indeed directly about my earnings through their publisher account. One suggestion they had for me to improve my earnings was to no longer restrict the job type (full-time, part-time etc). Is this at all possible? Otherwise, they seemed very impressed with the WP Job Manager setup! Thanks!

**Comment by mikejolley** [comment]
Actually it's not :) The API we use has job-type as a required param.

> jt	Job type. Allowed values: "fulltime", "parttime", "contract", "internship", "temporary".

So it's not possible to query multiple types with their API. :dragon_face:
