### ISSUE TITLE
Resume Manager Feature Suggestion

### ISSUE THREAD

**Issue by gumresq** [mikejolley/WP-Job-Manager#391]
If you are employed but looking for a new job, you probably do not want your current employer to see your posted resume and learn that you are looking for a new job want to quit the current job. I would like to suggest that resumes are kept confidential, only viewed when an applicant applies with the resume. Instead allow job seekers to fill in some unidentifiable information (education, experience, job position, desired work locations [list several i.e., LA, Calif, NY NY, New Orleans, LA, etc.] and so on). Then allow employers to invite candidates (after searching the above information) to apply for the job that the employers post.
It may require a new add on for WP Job Manager. It may be built into the core plugin.
 I hope it makes sense.
Thanks.
Scott

**Comment by mikejolley** [comment]
Thanks for the suggestion - I've moved this request to our private resume manager issue tracker.

Thanks!
