### ISSUE TITLE
Clone/copy Listings

### ISSUE THREAD

**Issue by cassim1** [mikejolley/WP-Job-Manager#393]
Hallo

So issues but a request.
I will very much like a clone/copy function to the WP Job Manager plugin (a function that also works on Listify)

**Comment by bryceadams** [comment]
Just use https://wordpress.org/plugins/duplicate-post/

**Comment by mikejolley** [comment]
^ yep thats supported.

**Comment by BenjaminZekavica** [comment]
It's don't work for the current version  :(

**Comment by richardmtl** [comment]
@BenjaminZekavica This is you, right? https://wordpress.org/support/topic/job-manager-add-action-to-dublicate-job/  As I mentioned there, this is already supported directly in the plugin, from the Jobs Dashboard. :)

**Comment by BenjaminZekavica** [comment]
Yes. I have installed the plugin its work, but its look terrible... 

![enter image description here](https://s2.imagebanana.com/file/180522/NEE9IGyA.png)

**Comment by richardmtl** [comment]
@BenjaminZekavica I don't understand the issue. An employer can duplicate job listings from their Jobs Dashboard. If you are unable to do that, please add more to the WordPress.org forum thread. Thanks!
