### ISSUE TITLE
Load More Listings overlays footer on Desktop.

### ISSUE THREAD

**Issue by ChrisSparks** [mikejolley/WP-Job-Manager#394]
Note: Using Indeed Integration Plugin

When using the default "Load More Listings", the listings jump our footer and overlay it. Any thoughts on how to fix?

We tried using Pagination. That solves the footer problem. But, when you click a page number, it displays results but keeps you at the bottom of the page. Is there a way to make it move back up to the top of the page so the user doesn't have to scroll back up? 

We like "Load More Listings" for mobile and would rather use it. But, I think both options might have a bug.

Thank you!

**Comment by ChrisSparks** [comment]
Also, Pagination is showing links to all pages in the search results. So when using popular search terms, there are as many as 1400 links within the pagination at the bottom of the page.

**Comment by mikejolley** [comment]
Send a link to your site to wpjobmanager.com/support/ with the details. I think your theme may be either forcing page height, or it may be missing a clearfix.
