### ISSUE TITLE
Customize email results after application is submitted

### ISSUE THREAD

**Issue by MicheleKing** [mikejolley/WP-Job-Manager#396]
Hi there,

Is it possible to customize the email reply that goes to the applicant after a resume has been submitted and if so, can you please direct me to the documentation?

Thank you!

Michele

**Comment by bryceadams** [comment]
Please open a ticket through the website :)

**Comment by mikejolley** [comment]
Yeah, please use wpjobmanager.com/support/. Need clarification on email, since resume submission doesn't usually email the actual submitter.
