### ISSUE TITLE
Content entry message of job shortcode about days expiring take no account the setting

### ISSUE THREAD

**Issue by bluezmedia** [mikejolley/WP-Job-Manager#402]
Please see screenshot !

![2015-02-24_163644](https://cloud.githubusercontent.com/assets/11046808/6352490/63bbc42c-bc43-11e4-9700-e059d95126ca.jpg)

**Comment by mikejolley** [comment]
The setting refers to how long it takes for a published listing to expire.

The page refers to how long it takes for expired listings to be permanently deleted.
