### ISSUE TITLE
Submission form: Tab Checkboxes not working in Chrome

### ISSUE THREAD

**Issue by Campleiter** [mikejolley/WP-Job-Manager#403]
Hello Support-Team,

on my Website the check-boxes in the submition-Form can not be clicked while using chrome. In Firefox this works great.

Is this a known issue?

Waht info do you need to fix this?

Best Wishes 
Camp

**Comment by mikejolley** [comment]
No I don't think so  -got a link?

**Comment by scottbasgaard** [comment]
Can look into this further as well, unable to replicate locally or on http://demo.wpjobmanager.com/ though…

@Campleiter can you replicate on our demo site or is this specific to your install?

**Comment by mikejolley** [comment]
Contact via wpjobmanager.com/support/  or wpjobmanager.com/contact/. Cannot do anything without more details. Closing this issue as this isn't the place for support requests.

**Comment by Campleiter** [comment]
Hi Mikejolley,

here is the link:
http://ausgehen-in-osnabrueck.de/eintrag-einreichen/
(pw: findos123)

WP 4.1.
Browser: Chrome (40.0.2214.115 m)
not able to mark the checkboxes for types.

As you say here is no support-place, the Plugincreator relates here:
https://wpjobmanager.com/contact/ ...

Thank you very much for your Help.

**Comment by mikejolley** [comment]
@Campleiter don't post login details here - its public. Use the contact form, select pre-sales.

**Comment by Campleiter** [comment]
That were no login details... that was just for the frontend, because the website should not be accessed by locals today.

**Comment by mikejolley** [comment]
ok, regardless, please submit using the form so we can look properly.
