### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lockart** [mikejolley/WP-Job-Manager#404]
Hi my name is Arthur. I love you program. I installed it on my website. The URL is gumsling.com/hm/jobs . Only issue is when I (admin) create job and post them. When someone access the link they view the job, but at the top when you school down appear my wordpress admin toolbar. The one that allow me to add pages and access my dashboard. How can I correct this? I logout of wordpress access the page and the toolbar appears at the top of the page. The theme I'm using is Jarida.

**Comment by mikejolley** [comment]
I see it when logged out too - looks like a caching plugin is caching logged in requests. This is a misconfiguration with your caching plugin/server, not the plugin.

**Comment by lockart** [comment]
Any way I can correct it that you know of

**Comment by lockart** [comment]
or what theme works best with your program

**Comment by mikejolley** [comment]
Turn off the caching plugin or configure it correctly. It's nothing to do with the theme as far as I know.

**Comment by lockart** [comment]
ok

**Comment by lockart** [comment]
okay... that solved it. Thanks for your professionalism. I'll leave you a positive comment. Also I will upgrade when I get paid. Great plugin!!!
