### ISSUE TITLE
Applications custom post type update

### ISSUE THREAD

**Issue by itmaximus** [mikejolley/WP-Job-Manager#411]
Hello, 

Im using gravity form to submit application in job application custom post type it seems when the form is submitted I still need to go to applications and update the post again to be visible on the frontend. I have checked with gravity form and the contact-listing plugin which integrates with gravity form both ruled out the issue on there side. 

can you please check this.

**Comment by multibids** [comment]
I believe you will need to go to the support section of wpjobmanager.com and submit a ticket as the applications add-on is a paid extension.  Support is not handled here to my knowledge.  I'm only posting here as I would love to see what you find out when it's all said and done.

**Comment by mikejolley** [comment]
The issue won't be on their or our side - it will be the way you've setup your data. It may be the status - compare the data before and after for the application in the posts table.

Closing as this issue tracker is for core.
