### ISSUE TITLE
<br> Tags Inserted Into <input> Tags

### ISSUE THREAD

**Issue by TheBroox** [mikejolley/WP-Job-Manager#412]
I am having an issue with the [submit_job_form] slug. Inputs on the page are having `<br>` tags inserted into them and thus breaking the tag. Below you can see both a code snippet as well as a screenshot.

```HTML
<fieldset class="fieldset-job_title">
				<label for="job_title">Title</label></p>
<div class="field required-field">
					<input<br />
	type=&#8221;text&#8221;<br />
	class=&#8221;input-text&#8221;<br />
	name=&#8221;job_title&#8221;<br />
	id=&#8221;job_title&#8221;<br />
	placeholder=&#8221;&#8221;<br />
	value=&#8221;&#8221;<br />
	maxlength=&#8221;&#8221;<br />
	required	/>
				</div>
</fieldset>
```

![screen shot 2015-03-06 at 1 17 42 pm](https://cloud.githubusercontent.com/assets/3739814/6530957/347b9a9e-c403-11e4-90c7-9858b773ee32.png)

I have tried deactivating all other plugins on the site thinking that they may be conflicting but that made no change. It seems to be an issue with the slug itself.

**Comment by mikejolley** [comment]
The theme is adding line breaks by adding custom filters to 'the_content'. Seen it in a few themes from themeforest.

**Comment by mikejolley** [comment]
I'll leave this open because we can remove line breaks from the template files to workaround the issue partially, but ideally themes should stop messing with the WP default content filters.

**Comment by TheBroox** [comment]
Thanks. As a heads up this theme is from MH Themes.

**Comment by aamwolff** [comment]
how do we 'remove line breaks' from the template files?

**Comment by mikejolley** [comment]
See the commit which closed this issue, or wait for the next version, or prevent your theme filtering 'the_content'.

**Comment by TheBroox** [comment]
Just wanted to confirm that the change did indeed fix the problem on my end. Thank you!
