### ISSUE TITLE
Set _yoast_wpseo_opengraph-image to company logo

### ISSUE THREAD

**Issue by mikejolley** [mikejolley/WP-Job-Manager#413]

**Comment by scottbasgaard** [comment]
@mikejolley you think we should add this so Yoast pics it up or general og: tags that can be toggled on / off?

**Comment by mikejolley** [comment]
Probably just yoast for now.

**Comment by scottbasgaard** [comment]
:+1:

**Comment by mikejolley** [comment]
The filter would be better ... for now, I've made a gist to set it when a job is posted :) https://gist.github.com/mikejolley/1682412ecf76ac1afbbe

**Comment by scottbasgaard** [comment]
Nice one @mikejolley :+1:
