### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by LeaSzeiler** [mikejolley/WP-Job-Manager#415]
so far no problems with the wp job manager.
since a few days job postings are listed in the summary http://www.openforce.com/stellenangebote/ but result in a 404 page http://www.openforce.com/Job/test/

looking forward to your feedback!

**Comment by mikejolley** [comment]
Have you tried going to Settings > Permalinks and saving?

**Comment by LeaSzeiler** [comment]
without changing or saving anything, it suddenly worked out again. no idea what could have caused that

thanks for your quick reply.
