### ISSUE TITLE
WooCommerce Paid Listings - Pricing Page Template

### ISSUE THREAD

**Issue by juanopeth** [mikejolley/WP-Job-Manager#417]
Hello mikejolley,
The Pricing Page Template is not showing the "Job Packages" that I've created. The issue is just with the template because the widget "Jobify: Home Woocomerce Package" show the "Job Packages" fine.

The "Pricing - Resumes" Template works well and show the resumens.

I don´t know well if I have to write this to you or to the Astoundify team, so sorry if I´m wrong.

Thanks for your atention.

**Comment by mikejolley** [comment]
@juanopeth Astoundify - this page template is part of the theme.
