### ISSUE TITLE
Uploads going into wrong uploads folder

### ISSUE THREAD

**Issue by momofone** [mikejolley/WP-Job-Manager#422]
I don't know if this is a Listify or a Job Manager issue - but all uploads - images and cover image, have been going missing since the latest updates.  I found that there are two uploads folders and the missing images can be found in the new folder, but they don't appear on the listing or in the media library.

The two folders I have are:
job_listings 
job-manager-uploads

Since the update, the files are going into the latter folder but the Listify theme is only using the job_listings folder. I am using the field editor and this is causing issues with both uploads fields and other fields.

**Comment by mikejolley** [comment]
It should not matter which directory is used/filtered because the URL that is returned by the upload function should be the one which was *actually* used. Unless you have some code thats hardcoding in that URL everything should be working.

**Comment by spencerfinnell** [comment]
Yeah this is in Listify. With the `job_manager_upload_dir` filter in it's own function out of the class we can use it easily now. Will our call with that. Can close this.

**Comment by spencerfinnell** [comment]
But as @mikejolley said, the path shouldn't really matter. Everything should return a real path regardless of where the actual image lives.

**Comment by spencerfinnell** [comment]
Though I'm wondering how uploads are currently working:

https://github.com/mikejolley/WP-Job-Manager/blob/3ed5f6324abdc559a68205288d4c16a6ac8cd986/includes/forms/class-wp-job-manager-form-submit-job.php#L891

https://github.com/mikejolley/WP-Job-Manager/blob/3ed5f6324abdc559a68205288d4c16a6ac8cd986/includes/forms/class-wp-job-manager-form-submit-job.php#L896

`$upload` should be `$uploaded_file`, no?
