### ISSUE TITLE
Multiple Locations

### ISSUE THREAD

**Issue by jno87** [mikejolley/WP-Job-Manager#428]
Some companies have multiple locations. Is there a way to add multiple locations under one listing?

**Comment by fourfootweb** [comment]
This would be a fantastic feature,

**Comment by mikejolley** [comment]
We don't plan on supporting this one just yet, mainly due to geolocation. Jobs have 1:1 relationship with location, lat and long.

If you're looking for a quick way to dupe a job to list in other locations, you can use https://wordpress.org/plugins/duplicate-post/

**Comment by fourfootweb** [comment]
Fair enough Mike, thank you kindly for passing on that plugin, will help for sure
