### ISSUE TITLE
create custom form field

### ISSUE THREAD

**Issue by umiya** [mikejolley/WP-Job-Manager#431]
i want to add gender and city field into post a resume page of wp job manager how can i do this by creating my own code for that .pls help me

**Comment by mikejolley** [comment]
Please read the docs https://wpjobmanager.com/document/resume-manager-editing-submission-fields/

**Comment by umiya** [comment]
hello sir i check the link which you provide but i could not find for creating custom form field like radio button.In example they are use type equal to text but for radio button what type i use.pls reply me i am waiting for your answer.

**Comment by kochhase** [comment]
hello umiya,
or you use this here. 
https://plugins.smyl.es/docs/wp-job-manager-field-editor/changelog/
very easy to use.

**Comment by umiya** [comment]
hello sir thank you for your reply but i don't want to use plugin .i want to use some code that only add radio button so that i include gender field in my resume page of wp job manager plugin.i am waiting for your reply.

**Comment by mikejolley** [comment]
@umiya we don't support radio buttons - use a select box, they handle the same kind of data.

**Comment by umiya** [comment]
thank you sir for reply me.i am very thankful to you. can you show me some code for creating checkbox for gender field in which i can make restriction to select only one checkbox at a time.pls reply i am waiting for your answer

**Comment by mikejolley** [comment]
@umiya the doc I linked to has an example. Use type 'select' and define an array of 'options'. If you struggle with code, I strongly recommend the plugin for Smyles - its really good :)

**Comment by umiya** [comment]
thank you sir for giving me your valuable answer i am very happy by using your plugin and thank you so much for solving my problem...once again thank you...
