### ISSUE TITLE
Widget: Best reviewed

### ISSUE THREAD

**Issue by nicschouten** [mikejolley/WP-Job-Manager#433]
A great add-on to JM is a widget which displays the best reviewed listings. This will let everybody know what is a trusted en accepted listing.

**Comment by mikejolley** [comment]
This sounds custom tbh - how would you determine what is reviewed?

**Comment by nicschouten** [comment]
Well, from a technical perspective the reviews are available in the Posts table. I am using JM as a way to review listings from companies. This means I am not using is to get people to work but just to get people to the best company they desire. Everybody can review companies. This is why I would like to show the best reviewd companies (listings).

Do you understand what I am looking for?

**Comment by mikejolley** [comment]
Not 100%, but seeing as this is not the intended use case for the plugin it has no place in core. You should create this widget as a customisation.

Hope you understand.
