### ISSUE TITLE
Search is only WP JM enabled -> Enable the whole bunch!

### ISSUE THREAD

**Issue by nicschouten** [mikejolley/WP-Job-Manager#434]
Currently the [jobs] search bar only searches through the jobs/listings. If a developer wants to use this search bar as a full website search it won't fit. Why don't search throush pages, blogs, comments, etc to create a more advanced result.

**Comment by mikejolley** [comment]
Why would it? That's not relevant to jobs - remember the search is built into the [jobs] shortcode.
