### ISSUE TITLE
Seacht through listing content

### ISSUE THREAD

**Issue by nicschouten** [mikejolley/WP-Job-Manager#436]
When I desire to search for a word like 'tanden', the [jobs] sreach form doesn't return a result. This while a listing contains the word 'tandenknarsen'. When I search at 'tandenknarsen' it does return a result of my listing. Is it possible to search within listings with wildcards?

**Comment by mikejolley** [comment]
We do a full word search here: https://github.com/mikejolley/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L156 because it gives more relevant results that just a wildcard based search. You are free to customise this, but I feel for most users the full-word search will work better.
