### ISSUE TITLE
Cannot enter description data when creating a new job post

### ISSUE THREAD

**Issue by aeqquus** [mikejolley/WP-Job-Manager#438]
Input form for creating a new job is restricted.  Cannot enter a description for a new job postion, which is a required field.

**Comment by mikejolley** [comment]
You have a plugin conflict. Check the browser JavaScript error console.

**Comment by aeqquus** [comment]
Error log from IE.  Doesn't seem to relate to a plug-in conflict.  
![wp job manager error log](https://cloud.githubusercontent.com/assets/9135906/7128014/141fb758-e212-11e4-90e6-27d3747dbdd5.jpg)

**Comment by aeqquus** [comment]
This is possibly the culprit.  Where is 'wp-editor' defined?  What if I am using TinyMCE or other editor tool?
![wp-editor type](https://cloud.githubusercontent.com/assets/9135906/7128094/00606a86-e213-11e4-9af8-22c00608770e.jpg)

**Comment by aeqquus** [comment]
I changed the type above to text in the class script.  This worked OK but I can only get 255 or so chars in the field.  Is there a way to define the type as text-area and define #rows otherwise the problem is the wp-editor definition:  TinyMCE or other.  I installed WP Edit plugin and turned off Black?? TinyMCE widget.

**Comment by mikejolley** [comment]
tinymce/wpeditor is part of WordPress :) Its what you use in the backend. The error you're seeing us from a plugin which adds a new button to tinymce in the backend only, so it breaks frontend.

**Comment by aeqquus** [comment]
I inserted the short-code inside a text widget and it worked great.  Looking forward to using the plug-in.  Thank you.

**Comment by LocalProducer** [comment]
I am having the same issue with my front end.  http://guiribusiness.com/post-a-job/
Can you please advise?  Thank you
