### ISSUE TITLE
URL (permalink) problem

### ISSUE THREAD

**Issue by aeqquus** [mikejolley/WP-Job-Manager#440]
Whenver I click on a specific job in a listing (via short_code or widget) I get a page not found error.

This is the URL to a specific job post that is produced in the short_code listings and recent job list widget:
http://www.aeqquus.com/blog/job/aeqquus-corpus-christi-texas-7-test-job

This is the permalink in the back-end that links properly to the specific job listing page:
http://www.aeqquus.com/blog/?job_listing=aeqquus-corpus-christi-texas-7-test-job

Is there a specific permalink structure I need to use or where in the script is the URL generated (and what triggers the GUID update in the database?

Changing the permalink settings in the WP config and changing it back to page-id temporarily fixes the problem but it reverts back eventually.

**Comment by bryceadams** [comment]
What are you permalink settings - post name?

Try re-save your permalinks again.

**Comment by aeqquus** [comment]
It was numeric.  I changed to post-name and it works.  I’m probably getting a conflict somewhere with some other plugin. I’ll leave it set to post-name and see if that cause issues somewhere else.  I’m using about four different plugins for jobs, classified ads, business directory.  They are all tripping over each other.  It is working now but for how long?  Thanks.  At least now I can fix it and know what to look for.

**Comment by bryceadams** [comment]
Cool. Yeah, stick to post name, it's better.

@mikejolley can close.

**Comment by aeqquus** [comment]
Thank you.  I’ve played with WP for years but now trying to set up a real public site.  It needs to work consistently.  I like the Job Manager plug-in.  If it looks like I can build some traffic I’ll probably want the geo-coding.  Really good app.  Wish I could skin the other post listings like yours.
