### ISSUE TITLE
Job Applications FOrm bugs at latest version of WP Job Manager

### ISSUE THREAD

**Issue by ronoliverclarin** [mikejolley/WP-Job-Manager#441]
GOt this error
Fatal error: Cannot redeclare non static WP_Job_Manager_Form::$steps as static WP_Resume_Manager_Form_Submit_Resume::$steps in /home/merkadonetwork/public_html/wp-content/plugins/wp-job-manager-resumes/includes/forms/class-wp-resume-manager-form-submit-resume.php on line 1055

**Comment by mikejolley** [comment]
You need to update resumes.

**Comment by ronoliverclarin** [comment]
What do you mean by update?
 I tried to go to setting and click save but it's not working.

**Comment by mikejolley** [comment]
Update the plugin to 1.11

**Comment by ronoliverclarin** [comment]
Thanks.
