### ISSUE TITLE
Registration Form Error

### ISSUE THREAD

**Issue by ileisuresports** [mikejolley/WP-Job-Manager#442]
How can I fix the error that I receive on the Registration page ?

Fatal error: Cannot redeclare non static WP_Job_Manager_Form::$steps as static WP_Job_Manager_Form_Register::$steps in /home/webs/public_html/masterchefjobs.com/wp-content/themes/jobify/inc/integrations/wp-job-manager/wp-job-manager-form-register.php on line 288

I have installed the template on this website http://masterchefjobs.com/sign-up/

Many thanks in advance

**Comment by mikejolley** [comment]
You can upgrade jobify to 2.0.4.4

**Comment by mikejolley** [comment]
Yep confirmed; you need to update Jobify to their latest 2.0.4.4 release for compatibility. Thanks.
