### ISSUE TITLE
has active resume package option

### ISSUE THREAD

**Issue by nielszandsteeg** [mikejolley/WP-Job-Manager#443]
Hi,

Perhaps this suggest has been asked before, but I could't find it.

So is there an option to require active resume packages for browsing/viewing jobs like the settings of resumes has?

Thanks!

**Comment by mikejolley** [comment]
No; if you want this you should add permissions checks inside the template files (content-job_listing.php and content-single-job_listing.php) https://wpjobmanager.com/document/template-overrides/
