### ISSUE TITLE
WP Video Shortcode

### ISSUE THREAD

**Issue by spencerfinnell** [mikejolley/WP-Job-Manager#445]
https://github.com/mikejolley/WP-Job-Manager/blob/master/wp-job-manager-template.php#L406

Is causing some problems for people. It's not loading the actual YouTube or Vimeo player. Perhaps the `[embed]` shortcode would be better. I'll try and do some tests.

**Comment by spencerfinnell** [comment]
I'm still seeing the non-YouTube player on Storefront: http://www.screensnapr.com/3jr3z0zxwfwy

**Comment by mikejolley** [comment]
Look at 20-12. Same code, diff format.

**Comment by spencerfinnell** [comment]
Weird. Seems no matter where I call `the_company_video()` it's always not playing the video. Adding just  a YouTube URL in the description autoembeds it fine.

**Comment by mikejolley** [comment]
@spencerfinnell videos work and load fine in Storefront, jobify, default themes. Only in Listify do you get a blank video window. Audio only.

**Comment by mikejolley** [comment]
@spencerfinnell I may need to revert your suggestion - its not working/embedding videos like https://fast.wistia.net/embed/iframe/e0rk8yet5v

#blamespencer

**Comment by spencerfinnell** [comment]
If it's reverted what about locally uploaded videos? 

I've used code like this before which seems to work well in both scenarios: https://gist.github.com/spencerfinnell/745763dc6cf5c323d59d

**Comment by spencerfinnell** [comment]
I think reverting is fine but the upload link on the video field should be removed and it become a standard text field if it relies on oEmbed.
