### ISSUE TITLE
Using $this when not in object context in wp-content\plugins\wp-job-manager\includes\forms\class-wp-job-manager-form-submit-job.php

### ISSUE THREAD

**Issue by tenbulls007** [mikejolley/WP-Job-Manager#448]
Today i updated to latest version and then started getting that error on my submit job form please resolve that issue

**Comment by mikejolley** [comment]
You need to update the plugins/themes. 1.22 job manager requires resumes 1.11.x applications 2.0 and Jobify 2.0.4.4

**Comment by tenbulls007** [comment]
thanks it worked
