### ISSUE TITLE
ReCaptcha is not working

### ISSUE THREAD

**Issue by Kabney** [mikejolley/WP-Job-Manager#450]
I have set up my keys, added the code from github to get it to work on both the resume and job submission forms with my keys in it and it will only show me the error that it isn't working. Are you human check failed, please try again. Is there something I am missing or something i need to do differently? I have the latest versions of wordpress, Jobify and all plug-ins. 
Thanks!

**Comment by mikejolley** [comment]
This isn't really the place for these types of question; this is for core bug reports only..

It would be 1 of 2 things;

1.  your keys are wrong, or
2. your server is blocking the request to google

you could add, before "return new WP_Error( 'validation-error', '"Are you human" check failed. Please try again.' );" this to debug:

`var_dump( $response );`

**Comment by Kabney** [comment]
My apologies, that is where I was directed for support issues from the Job Manager site. If you would point me in the right direction as to where I should submit support tickets, I will use that from now on.
Thanks,
Kristin Abney
Webmaster & Project Manager
Cybervise Limited
kristin@cyberviselimited.com
513-351-6710 or 513-510-4962
Toll Free 1-800-813-8479

**Comment by mikejolley** [comment]
The community forum is here https://wordpress.org/plugins/wp-job-manager/. Please see my debug suggestion above before asking for more help :)

**Comment by Kabney** [comment]
will do ,thx

Kristin Abney
Webmaster & Project Manager
Cybervise Limited
kristin@cyberviselimited.com
513-351-6710 or 513-510-4962
Toll Free 1-800-813-8479
