### ISSUE TITLE
Conflict with CM Tooltip Glossary Plugin

### ISSUE THREAD

**Issue by em31245** [mikejolley/WP-Job-Manager#451]
When CM Tooltip Glossary plugin is enabled, the list of open jobs does not display on the page. The keywords and Location search box along with job type check boxes display, but the actual job postings do not display. I disabled all plugins and enabled them one by one to determine what was causing the issue.

**Comment by mikejolley** [comment]
Shouldn't this be reported to CM Tooltip Glossary? No doubt they are causing a jquery error. I can check if you send a link to your page.

**Comment by mikejolley** [comment]
Closing due to lack of feedback.
