### ISSUE TITLE
WordPress 4.2 Orderby enhancements

### ISSUE THREAD

**Issue by mikejolley** [mikejolley/WP-Job-Manager#452]

**Comment by kochhase** [comment]
Hi Mike,
is there a way to enhance the search to a "relevance search" . something like if I don´t find some job as Roofers also find jobs as a carpenter or joiner. Or is there an addon planed for an "advanced" search?

**Comment by mikejolley** [comment]
@kochhase no plans for that at the moment. Sounds very complex to be honest.
