### ISSUE TITLE
Job labels overlapping fields

### ISSUE THREAD

**Issue by willie300** [mikejolley/WP-Job-Manager#453]
Hi,

Am having an issue after updating to 1.22.3. When adding or editing a job listing on the backend.
The job data area looks distorted as the picture illustrates.
![job manager issue](https://cloud.githubusercontent.com/assets/3899177/7337168/fa14c69e-ec27-11e4-9c89-071ad56889c1.PNG)

Please assist.

**Comment by mikejolley** [comment]
Clear browser cache.

**Comment by willie300** [comment]
I tried that but it didn't help. Even tried the dashboard on my smartphone and different browsers. Gave me the same error.

**Comment by mikejolley** [comment]
If its not browser cache, its because you have an older version of resumes or applications. All need updating to clear up the styles.

**Comment by willie300** [comment]
Thank you, that fixed it.
