### ISSUE TITLE
Feature Request: Extra License for Staging Server

### ISSUE THREAD

**Issue by fraximus** [mikejolley/WP-Job-Manager#457]
It would be soooo helpful and save a ton of time to have a license that can work in both Staging and Production areas.Any chance of that happening?

**Comment by kim07** [comment]
:+1:

**Comment by batsteek** [comment]
Yeah, same need here.

**Comment by tripflex** [comment]
If you're using a staging server you could just setup an rsync cron job or something between the two, or if they are on the same server just use a symlink

**Comment by mikejolley** [comment]
Yeah we can do this.
