### ISSUE TITLE
update resume field using WP job manger field editor

### ISSUE THREAD

**Issue by umiya** [mikejolley/WP-Job-Manager#458]
hello sir i want update education and experience field in  post a resume page .
i have already by WP job field editor plugin .but when i am using this plugin for updating education and experience field .it is not working and say "You do not have sufficient permissions to access this page."
what can i do .pls help me i am waiting for your answer

**Comment by umiya** [comment]
hey sir why you are not giving reply to  me

**Comment by bryceadams** [comment]
@umiya if you are already a customer, please open a ticket here - https://wpjobmanager.com/support/

For the WP Job Field Editor plugin, contact the author of it https://plugins.smyl.es/wp-job-manager-field-editor/?in=1

**Comment by umiya** [comment]
OK sir thank you for reply.

**Comment by gravitymaster97** [comment]
<a href="https://wordpress.org/plugins/custom-field-for-wp-job-manager/">Custom Field For WP Job Manager</a> plugin allow you to add custom field text and select box
