### ISSUE TITLE
1.22.0+ Admin area layout formatting

### ISSUE THREAD

**Issue by tripflex** [mikejolley/WP-Job-Manager#460]
Having a few issues with the new layout format because the wrapper div is using `overflow: hidden;`

![](https://smyl.es/img/Selection-05-12-2015-235.png)

I was going to just code it to set `bottom: 100%;` to have the dropdown open upwards but it may be better to look at possibly redoing the layout.  What are your thoughts?

I was thinking maybe using the float left and having each additional field stack and wrap in the meta box?

I know Astoundify was having a few issues with the map and another field or two as well, but maybe if we looked at another format we could then get fields like the business hours to not take up the full meta box height for that field:

![](https://smyl.es/img/Selection-05-13-2015-659.png)

So in screenshot above, Listing Expiry Date would be right under Company Video, instead of being pushed down due to using float left and float right....

Thoughts?

**Comment by spencerfinnell** [comment]
+1

Another thought might be to have a separate meta box for the company fields as well. This would help split things up and the separate boxes can be toggled independently.

**Comment by adampickering** [comment]
:+1: Dislike the current layout of Job Data.

**Comment by opusuno** [comment]
@adampickering Hate to try and contact you this way but in a crunch and this way i know you'll be notified.

I have a customer that wants to list paid events for the horse world. 

Is it possible with one of your themes to categorize for example: Dressage, Roping, Horsemanship events and thence able to search by trainer and location? 

Which of your theme's would be best  for something like this?

Regards 

My email is steve@opusuno.com

**Comment by adampickering** [comment]
All pre-sales question are conducted over on ThemeForest.net @opusuno

**Comment by opusuno** [comment]
Got it.. 

Steve B.

steve@opusuno.com




On May 25, 2015, at 10:32 AM, Adam Pickering <notifications@github.com> wrote:

All pre-sales question are conducted over on ThemeForest.net @opusuno

**Comment by mikejolley** [comment]
We can fix the overflow issue.

As for the larger data areas, such as business hours, I'd argue they deserve their own widget as they will take over *any* layout of fields. Like we do in Resume Manager; education, experience can grow so they go in their own meta boxes.
