### ISSUE TITLE
Payment Gateway Confirming Payment Error

### ISSUE THREAD

**Issue by joshlocal** [mikejolley/WP-Job-Manager#466]
Attempted to purchase the LinkedIn login plugin 5 times with multiple browsers. Payment confirmed green via Stripe every time, yet account is still showing that I have not purchased the plugin. Never received confirmation error either. Hoping I'm not getting charged 4 extra times for the plugin.

**Comment by mikejolley** [comment]
It would have been failed. Try paypal using a credit card. Use https://wpjobmanager.com/contact/ if you have further problems.
