### ISSUE TITLE
Option to Remove Address from Slug

### ISSUE THREAD

**Issue by spencerfinnell** [mikejolley/WP-Job-Manager#470]
Right now there isn't a way (easily) to not have the address prepended to the listing slug. We have *lots* of people asking how to remove this. Any chance for a filter that will skip that step?

**Comment by MaverickWar** [comment]
Need this also, the current URL is unsightly and i cannot use it live on my website in its current format.

**Comment by mikejolley** [comment]
https://wpjobmanager.com/document/tutorial-changing-the-job-slugpermalink/

**Comment by MaverickWar** [comment]
Hi and thanks mike but that doesnt really help. What do we remove to have only thr url base/listing/company name with no address.

**Comment by mikejolley** [comment]
You can change/add what you want. Adapt "Changing the permalink slug for new jobs" snippet.
