### ISSUE TITLE
Upgrade to wordpress 4.2.2

### ISSUE THREAD

**Issue by dtdave** [mikejolley/WP-Job-Manager#472]
When upgrading to 4.2.2 pages are formatted properly if accessing via https but not when using http.

I am using Vantage child theme but have tried it with Vantage as well. Deactivating the WP Job Manager makes everything fine.

Any help would be appreciated.

**Comment by mikejolley** [comment]
I don't see how HTTPS would affect anything unless resources such as CSS fail to load. Link?

**Comment by dtdave** [comment]
Thanks for the reply. Found the problem mod_pagespeed was the issue.

Best
