### ISSUE TITLE
Apply button not working in firefox

### ISSUE THREAD

**Issue by yetsun** [mikejolley/WP-Job-Manager#474]
Hi, 
The Apply button on the job detail page is not working in firefox. 
The button has no text in it. 

My firefox version is 38.0.1

Thanks,
Jun

**Comment by mikejolley** [comment]
Need a link to the affected site. I assume it does not happen on demo.wpjobmanager.com for you?

**Comment by mikejolley** [comment]
Closed due to lack of feedback.
