### ISSUE TITLE
Add Text within application

### ISSUE THREAD

**Issue by familyhealthcare** [mikejolley/WP-Job-Manager#477]
Hi Mike-

We'd like to be able to just put some short paragraphs within our application form. The current form only allows fields to be inserted. Is there anyway you could make a modification so that you could add some simple text within the form without needing a field to go with it? This is the last part to us making the switch to your widget.

**Comment by mikejolley** [comment]
Does it need to be inline? You can edit the templates to add text above/below the form.

**Comment by familyhealthcare** [comment]
Preferably. We’d like to put the legal text in about applying with us and the non discrimination policy and then have them type their name and date. Also, we’d like to be able to label each section of the form. Ie. History, personal, job preferences.

**Comment by mikejolley** [comment]
Ok, Im going to close this and log it in the correct place.

Thanks
