### ISSUE TITLE
feature request: WP Jetpack Publicize 

### ISSUE THREAD

**Issue by Designerplus** [mikejolley/WP-Job-Manager#480]
Integrate jetpack publicize feature with CUSTOM POST TYPE theme or make a snippet in de support doc to make it done. 

This is how its done:

You can add Publicize support to an existing post type thanks to the add_post_type_support() function. To do so, add the following code to a functionality plugin:

add_action(‘init’, ‘my_custom_init’); function my_custom_init() { add_post_type_support( ‘product’, ‘publicize’ ); }

You’ll need to replace “product” by your Custom Post Type name, but cant find for what??

Please Help how to fix this!

Kind regards

Ray

**Comment by mikejolley** [comment]
It is already there https://github.com/mikejolley/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L205
