### ISSUE TITLE
Geocode Alerts

### ISSUE THREAD

**Issue by dfaraco** [mikejolley/WP-Job-Manager#482]
It would be good if the alerts could be refined by location. Some jobs may just be too far away. If the user could set their alerts like so: Within 100 mi. - Within 500 mi. - Nationwide - Worldwide (all).

**Comment by wmacmill** [comment]
I agree that would be awesome. Currently alerts does work with the predefined regions plugin https://wordpress.org/plugins/wp-job-manager-locations/

**Comment by mikejolley** [comment]
This could be handled by one of the geolocation plugins to calc the distance/lat/long. I will log in the correct repository. Thanks.
