### ISSUE TITLE
Configure Resume Access For Specific Packages

### ISSUE THREAD

**Issue by dougherty6504** [mikejolley/WP-Job-Manager#486]
Hi.. I was wondering if you could only allow access for a specific package? for example
I would like to have 3 job packages: basic, featured and featured plus. Featured Plus would be the only package which allows users to view resumes. If this is possible would you kindly post the code and how to implement it? Many thanks Keith

**Comment by mikejolley** [comment]
This issue tracker is for core only. Not paid addons.

We have some snippets which can be adapted for your requirements https://wpjobmanager.com/document/tutorial-require-an-active-job-package-to-view-resumes/

**Comment by dougherty6504** [comment]
Hi Mike

Thanks for you quick response.. And apologies if I posted in the wrong
place.

I would be really grateful if you could let me know how to adapt the code
to make the resumes only visible for a specifics package. I know it's
probably not something you woul usually do but you would really helping me
out. I'm also sure someone else will probably ask for the same thing in the
future.

Many thanks

Keith
