### ISSUE TITLE
Feature request: limit amount of gallery images based on paid listing package

### ISSUE THREAD

**Issue by dvdmierden** [mikejolley/WP-Job-Manager#487]
We're using WC Paid Listings plugin to allow company owners to place listings with more or less fields. I managed to add an additional video field if a "Gold" package is bought, and removed the telephone field if only a "Silver" package is bought. So far so good.

Now I want to allow "Gold" package buyers to upload, say, 5 gallery images, whereas "Silver" package buyers are only allowed to upload 2 gallery images. 

Any thoughts?

**Comment by mikejolley** [comment]
I assume you're using the field editor to allow different fields per package? I think this would fit into that feature set, rather than wc paid listings which does not limit fields itself.

This issue tracker is for core only btw. Not paid addons.
