### ISSUE TITLE
Plugin doesn't work after recent update - ajax issue?

### ISSUE THREAD

**Issue by peytonggregory1** [mikejolley/WP-Job-Manager#488]
First of all, great plug-in. I use it on several sites and my clients are always happy with it.

http://www.corerva.com/careers/

This plugin was working on this site until I updated the plugin today. Now, when you go to the careers page you'll see at the bottom of the pages there's a loading circle but the jobs never actually load. 

Is this a problem a lot of people are dealing with or could it be an issue with the theme? Do you have an older version I could use in the meantime?

**Comment by mikejolley** [comment]
Just go to Settings > Permalinks and hit save. Should clear it up.

**Comment by mikejolley** [comment]
Confirmed - you have a 404.

**Comment by peytonggregory1** [comment]
Awesome, thank you!
